# us
[timing.intervals]
sample = 250
adjust = 100_000

[gpu-usage]
fix-metrics = true
method = "busy-flag" # "busy-flag" or "process"
flush-every = 10

[gpu]
set-method = "smu"  # "smu" or "kernel"

[dbus]
enabled = true

# Limites de frequência (Destravado para até 2100MHz)
[frequency-range]
min = 350    # MHz
max = 1700   # MHz

min_voltage = 700     # mV
max_voltage = 1000    # mV

# MHz/ms
[timing.ramp-rates]
normal = 1
burst = 50

# number of samples
[timing]
burst-samples = 60
down-events = 5

# MHz
[frequency-thresholds]
adjust = 10

# Alvo de carga (Corrigido para evitar duplicidade)
[load-target]
upper = 0.65
lower = 0.50

# °C (Mantido seguro em 85 graus)
[temperature]
throttling = 85
throttling_recovery = 75

# Curva de Tensão/Frequência (Otimizada e Segura)
[[safe-points]]
frequency = 350
voltage = 700

[[safe-points]]
frequency = 1000
voltage = 700

[[safe-points]]
frequency = 1500
voltage = 900

[[safe-points]]
frequency = 1600
voltage = 900

[[safe-points]]
frequency = 1700
voltage = 920

[[safe-points]]
frequency = 1800
voltage = 940

[[safe-points]]
frequency = 2000
voltage = 960

[[safe-points]]
frequency = 2100
voltage = 1000
