---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-bc250
description: Bazzite com aic8800d80, 40cu unlock e smu oc
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - gcc
      - make
      - kernel-devel
      - kernel-headers

  - type: script
    scripts:
      - build-wifi.sh
      - build-bc250-mods.sh